import Head from "next/head";
import SlidingIconButton from "../components/SlidingIconButton";
import ArrowLongDown from "../components/icons/ArrowLongDown";
import ArrowLongRight from "../components/icons/ArrowLongRight";
import CatProfileBox from "../components/CatProfileBox";
import SlidersHorizontal from "../components/icons/SlidersHorizontal";
import User from "../components/icons/User";
import Bulb from "../components/icons/Bulb";
import Library from "../components/icons/Library";
import Beaker from "../components/icons/Beaker";

const cats = [
  { name: "Tom", url: "http://placekitten.com/g/300/300" },
  { name: "Orion", url: "http://placekitten.com/g/300/300" },
  { name: "Maximillian", url: "http://placekitten.com/g/300/300" },
  { name: "Schrodinger", url: "http://placekitten.com/g/300/300" },
  { name: "Bleb", url: "http://placekitten.com/g/300/300" },
  { name: "Oppenheimer", url: "http://placekitten.com/g/300/300" },
];

const cards = [
  {
    icon: <Bulb />,
    text: "Innovative products",
    subtext:
      'Made in CatLand, awwsome, super cute certified, "home automation NOT ready".',
  },
  {
    icon: <Library />,
    text: "Cat: what thinking?",
    subtext:
      "No one knows what goes in a cat's mind. So your guess is as good as mine :)",
  },
  {
    icon: <Beaker />,
    text: "Cuddlicious and lazy af",
    subtext:
      "All cats are super cute and adorable. Except the one that looks like a rat. Hairless. Idk why people like them. To each their own ig.",
  },
];

const Card = ({
  icon,
  classes,
  title,
  subtext,
}: {
  icon: React.ReactNode;
  classes: string;
  title: string;
  subtext: string;
}) => (
  <div className={`col-span-2 flex flex-col gap-10 ${classes}`}>
    <span className="h-10 w-10">{icon}</span>
    <h3 className="text-3xl">{title}</h3>
    <p>{subtext}</p>
  </div>
);

export default function Home() {
  return (
    <>
      <Head>
        <title>MODELEC clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#2f3035] p-10 pt-36 grid grid-cols-12">
        <button className="self-end text-white">
          <ArrowLongDown />
        </button>
        <p className="text-3xl col-start-4 col-span-4 text-white">
          I curated some high-end cat photos from raw material (cats). Made in
          CatLand since forever.
        </p>
      </div>
      <div className="h-auto relative p-12">
        <div className="grid relative aspect-[2500/1473]">
          <img
            className="row-start-1 col-start-1 relative z-10 w-full rounded-xl"
            src="https://placekitten.com/1369/806"
          />
          <div className="heroTextGradient row-start-1 col-start-1 self-end w-full pl-20 pr-12 pb-8 z-20 sticky bottom-0 text-white rounded-xl">
            <h3>New finishes: brown and white fur.</h3>
            <div className="flex justify-between items-center mt-6">
              <h1 className="text-8xl">Cat Collection</h1>
              <SlidingIconButton
                icon={<ArrowLongRight />}
                text="Discover the collection"
                classes="bg-white text-black"
              />
            </div>
          </div>
        </div>
        <div className="absolute top-0 left-0 bg-[#2f3035] h-1/2 w-full" />
      </div>
      <div className="bg-white">
        <div className="flex justify-between py-16 px-10">
          <h5>Collections</h5>
          <p>navs</p>
        </div>
        <div className="max-w-full overflow-hidden">
          <div className="scrollInfinite flex w-max gap-10">
            {cats.concat(cats).map((c, i) => (
              <CatProfileBox key={`cat#${i}`} name={c.name} url={c.url} />
            ))}
          </div>
        </div>
        <div className="flex justify-center py-20">
          <SlidingIconButton
            icon={<ArrowLongRight />}
            text="View all cats"
            classes="border-black border px-5"
          />
        </div>
      </div>
      <div className="flex px-10 py-20">
        <div className="flex-1">
          <img src="http://placekitten.com/g/800/800" className="rounded-xl" />
        </div>
        <div className="flex-1">
          <div className="h-full flex justify-center flex-col gap-10 px-40">
            <h3>Configurator</h3>
            <p className="text-3xl">
              Customise your feline with custom rockets, jetpacks, rollerblades
              and drip that will make an adult shed a tear. Carry it around and
              flex it on your counterparts with the love and affection
              paralleled with very little in this world.
            </p>
            <SlidingIconButton
              icon={<SlidersHorizontal />}
              text="Open the configurator"
              classes="bg-[#2f3035] text-white w-fit"
            />
          </div>
        </div>
      </div>
      <div className="flex px-10 py-20 bg-[#cfd2df]">
        <div className="flex-1">
          <div className="h-full flex justify-center flex-col gap-10 px-40">
            <h3>3D Visualization</h3>
            <p className="text-3xl">
              You can scan your feline to and make a 3D cat and share it around
              for other people to appreciate.
            </p>
            <p className="text-3xl">
              Maybe cool people can use Augumented Reality to feel the cat in
              the real world with, idk the stupid Apple VR headset?
            </p>
            <SlidingIconButton
              icon={<ArrowLongRight />}
              text="3D scan your feline"
              classes="bg-[#2f3035] text-white w-fit px-5"
            />
          </div>
        </div>
        <div className="flex-1 grid grid-cols-1 grid-rows-1 items-center justify-items-center isolate">
          <img
            className="col-start-1 row-start-1 z-10 rounded-xl"
            src="/mobile.png"
          />
          <img
            className="ml-1 col-start-1 row-start-1 rounded-[4rem]"
            src="http://placekitten.com/g/410/823"
          />
        </div>
      </div>
      <div className="flex px-10 py-20">
        <div className="flex-1">
          <div className="h-full flex justify-center flex-col gap-10 px-40">
            <h3>Configurator</h3>
            <p className="text-3xl">
              Experts can help you give more love and affection to your feline
              with tips and techniques along with specialized tools.
            </p>
            <SlidingIconButton
              icon={<ArrowLongRight />}
              text="Search experts"
              classes="bg-[#2f3035] text-white w-fit"
            />
          </div>
        </div>
        <div className="flex-1">
          <img src="http://placekitten.com/g/800/800" className="rounded-xl" />
        </div>
      </div>
      <div className="contactGradient">
        <div className="flex gap-10 px-40 py-20">
          <div className="flex-1">
            <div className="h-full bg-[#eee] flex justify-center flex-col gap-10 p-16 rounded-2xl">
              <h3>Professionals</h3>
              <p className="text-3xl">
                Professionals, we are here to accompany you in your project.
              </p>
              <SlidingIconButton
                icon={<User />}
                text="Log in"
                classes="bg-[#2f3035] text-white w-fit"
              />
            </div>
          </div>
          <div className="flex-1">
            <div className="h-full bg-[#2f3035] text-white flex justify-center flex-col gap-10 p-16 rounded-2xl">
              <h3>Contact us</h3>
              <p className="text-3xl">
                A question? A project? We are at your disposal to answer it.
              </p>
              <SlidingIconButton
                icon={<ArrowLongRight />}
                text="Search experts"
                classes="bg-white text-black w-fit"
              />
            </div>
          </div>
        </div>
        <div className="grid grid-cols-12 pt-24 px-9 pb-32">
          {cards.map((c, i) => (
            <Card
              key={`card#${i}`}
              classes={
                i == 0 ? "col-start-3" : i === 1 ? "col-start-6" : "col-start-9"
              }
              icon={c.icon}
              title={c.text}
              subtext={c.subtext}
            />
          ))}
        </div>
      </div>
      <p className="text-center py-40 text-2xl">
        This aint complete. I was cloning this site{" "}
        <a className="underline" href="https://www.modelec.com/en">
          https://www.modelec.com/en
        </a>
      </p>
    </>
  );
}
